# Generated by Django 4.1.3 on 2022-11-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="order",
            field=models.PositiveSmallIntegerField(
                null=True, verbose_name="Order in the Top100 list"
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="release_date",
            field=models.DateField(null=True, verbose_name="Release Date"),
        ),
    ]
