# Generated by Django 4.1.3 on 2022-11-03 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0002_song_order_song_release_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="song",
            options={"ordering": ["order", "release_date", "name"]},
        ),
    ]
