# Generated by Django 4.1.3 on 2022-11-03 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0003_alter_song_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["name"]},
        ),
    ]
